(()=>{"use strict";
const LEAD_ENDPOINT="https://wuwgvtjktppjueiykcww.supabase.co/functions/v1/website-lead-capture",BUSINESS_PHONE="(864) 446-8911",BUSINESS_PHONE_URL="tel:+18644468911";
const ham=document.getElementById("ham"),mobileNav=document.getElementById("mobileNav");
if(ham&&mobileNav){ham.addEventListener("click",()=>{mobileNav.classList.toggle("open");ham.setAttribute("aria-expanded",mobileNav.classList.contains("open")?"true":"false")});mobileNav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{mobileNav.classList.remove("open");ham.setAttribute("aria-expanded","false")}))}
document.querySelectorAll(".faq-q").forEach(q=>q.addEventListener("click",()=>{const open=q.classList.toggle("open"),a=q.nextElementSibling;if(a)a.classList.toggle("open",open);q.setAttribute("aria-expanded",open?"true":"false")}));
function ensureHoneypot(form){if(form.querySelector('input[name="website"]'))return;const trap=document.createElement("input");Object.assign(trap,{type:"text",name:"website",tabIndex:-1,autocomplete:"off"});trap.setAttribute("aria-hidden","true");trap.style.cssText="position:absolute;left:-9999px;width:1px;height:1px;opacity:0";form.appendChild(trap)}
function showFormError(form,message){let error=form.querySelector(".form-error");if(!error){error=document.createElement("div");error.className="form-error";error.setAttribute("role","alert");error.style.cssText="display:none;background:#fee2e2;border:1px solid #fca5a5;border-radius:6px;padding:.75rem .9rem;margin-bottom:.8rem;color:#7f1d1d;font-weight:600;font-size:.88rem";const success=form.querySelector(".form-success");success?success.insertAdjacentElement("afterend",error):form.prepend(error)}error.textContent=message;error.style.display="block"}
function clearFormError(form){const e=form.querySelector(".form-error");if(e)e.style.display="none"}
document.querySelectorAll("form.lead-form").forEach(form=>{ensureHoneypot(form);form.addEventListener("submit",async event=>{event.preventDefault();if(form.dataset.submitting==="true")return;clearFormError(form);const success=form.querySelector(".form-success");if(success)success.classList.remove("show");const data=new FormData(form),payload={name:String(data.get("name")||""),phone:String(data.get("phone")||""),email:String(data.get("email")||""),city:String(data.get("city")||""),service:String(data.get("service")||""),message:String(data.get("message")||""),website:String(data.get("website")||""),source_page:window.location.pathname||"/",form_id:form.id||"lead_form"};if(/^select/i.test(payload.service))payload.service="";if(!payload.service&&!payload.message)payload.message="Callback requested from website";const button=form.querySelector('button[type="submit"]'),original=button?button.textContent:"";form.dataset.submitting="true";if(button){button.disabled=true;button.textContent="Sending…"}try{const response=await fetch(LEAD_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});let result={};try{result=await response.json()}catch(_e){}if(!response.ok||!result.ok)throw new Error(result.error||"Request could not be sent");if(success){if(result.emergency)success.innerHTML='✅ Request received. This sounds urgent — please <a href="'+BUSINESS_PHONE_URL+'" style="color:var(--green-dk)">call '+BUSINESS_PHONE+' now</a> for the fastest response.';success.classList.add("show")}form.querySelectorAll("input,select,textarea,button").forEach(c=>c.disabled=true);if(typeof gtag==="function")gtag("event","generate_lead",{form_id:form.id||"lead_form",lead_source:"supabase_crm"})}catch(error){console.error("[PP911 Lead Form]",error);showFormError(form,"We couldn't send your request. Please call "+BUSINESS_PHONE+" so we don't miss you.");form.dataset.submitting="false";if(button){button.disabled=false;button.textContent=original}if(typeof gtag==="function")gtag("event","lead_submit_error",{form_id:form.id||"lead_form"})}})});
document.querySelectorAll('a[href^="tel:"]').forEach(link=>link.addEventListener("click",()=>{if(typeof gtag==="function")gtag("event","phone_click",{phone:"864-446-8911",location:document.body.dataset.page||"site"})}));
})();

(()=>{
const CONFIG={priceMultiplier:1,discountPercent:10,serviceCallFees:{regular:79,after:99,midnight:158,holiday:158}};window.PP911_PRICING_CONFIG=CONFIG;
const path=(window.location.pathname||"/").replace(/\/+$/,"")||"/",money=v=>"$"+Math.round(v).toLocaleString(),scaled=v=>v===null?null:Math.round(v*CONFIG.priceMultiplier),rangeText=(low,high)=>low===null?"Call for current price":high===null||high===low?"From "+money(low):money(low)+" – "+money(high);
function addLakeAreaLinks(){if(path==="/service-areas"){const grid=document.querySelector("main .grid-4");if(grid&&!grid.querySelector('[href="/service-areas/iva-lake-secession-sc/"]'))grid.insertAdjacentHTML("afterbegin",'<a class="nav-card" href="/service-areas/iva-lake-secession-sc/"><h3>💧 Iva &amp; Lake Secession, SC</h3><p>Well pumps, lake homes &amp; rural plumbing.</p><span class="arrow">Iva &amp; Lake Secession plumber →</span></a><a class="nav-card" href="/service-areas/savannah-lakes-village-sc/"><h3>🏡 Savannah Lakes Village, SC</h3><p>Well pumps, lift pumps &amp; second-home plumbing.</p><span class="arrow">Savannah Lakes Village plumber →</span></a>');const summary=document.querySelector(".page-header .speakable-summary");if(summary)summary.textContent="Serving Upstate South Carolina with extra focus on lake and rural communities where well pumps, pressure systems and second-home plumbing matter most."}if(path==="/services/well-pump-repair"){const hero=document.querySelector(".service-hero");if(hero&&!document.getElementById("lake-area-well-pump-focus"))hero.insertAdjacentHTML("afterend",'<section id="lake-area-well-pump-focus" class="section" style="padding-top:34px;padding-bottom:34px"><div class="container"><div style="background:var(--blue-xlt);border:1.5px solid #90CAF9;border-radius:var(--r2);padding:26px"><span class="label">Priority Well-Pump Markets</span><h2 style="font-size:1.45rem;margin:6px 0 10px">Lake Secession, Iva, McCormick &amp; Savannah Lakes Village</h2><p style="color:var(--ink2);margin-bottom:16px">Extra focus on lake and rural properties where a failed well pump or pressure system can shut the entire home down.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn btn-blue btn-sm" href="/service-areas/iva-lake-secession-sc/">Iva &amp; Lake Secession →</a><a class="btn btn-blue btn-sm" href="/service-areas/savannah-lakes-village-sc/">Savannah Lakes Village →</a><a class="btn btn-blue btn-sm" href="/service-areas/mccormick-sc/">McCormick →</a></div></div></div></section>')}}
function updatePricingPageCopy(){if(path!=="/pricing")return;document.title="Upfront Plumbing Pricing & Price Estimator | Plumbing Paramedic 911";const meta=document.querySelector('meta[name="description"]');if(meta)meta.content="Upfront flat-rate plumbing pricing from Plumbing Paramedic 911. Service calls: $79 regular hours, $99 after-hours/weekends, $158 after midnight or holidays. Repair prices approved before work starts.";['meta[property="og:description"]','meta[name="twitter:description"]'].forEach(s=>{const el=document.querySelector(s);if(el&&meta)el.content=meta.content});
const p=[...document.querySelectorAll("main p")].find(el=>el.textContent.includes("Every price includes labor and standard materials"));if(p)p.textContent="Our estimator gives you a useful starting point before you call. Repair pricing is flat-rate, and the service/diagnostic call is shown separately: $79 during regular hours, $99 after hours or on weekends, and $158 after midnight or on holidays. Any additional work is priced before you authorize it.";
const li=[...document.querySelectorAll(".check-list li")].find(el=>el.textContent.includes("Military"));if(li)li.textContent="10% military, veteran, senior and first-responder discount; discounts do not stack";
const faq=[...document.querySelectorAll(".faq-item")].find(item=>{const q=item.querySelector(".faq-q");return q&&/service call|diagnostic fee/i.test(q.textContent)});if(faq){const a=faq.querySelector(".faq-a");if(a)a.textContent="Yes. The service/diagnostic call is $79 Monday–Friday from 9 AM to 5 PM, $99 after hours and on weekends, and $158 after midnight or on holidays. Repair and installation prices are quoted upfront before work starts."}
document.querySelectorAll("script[type='application/ld+json']").forEach(script=>{try{const data=JSON.parse(script.textContent),nodes=data&&data['@graph'];if(!Array.isArray(nodes))return;nodes.forEach(node=>{if(node['@type']!=="FAQPage"||!Array.isArray(node.mainEntity))return;node.mainEntity.forEach(item=>{if(/service call|diagnostic fee/i.test(item.name||"")&&item.acceptedAnswer)item.acceptedAnswer.text="The service/diagnostic call is $79 Monday–Friday from 9 AM to 5 PM, $99 after hours and on weekends, and $158 after midnight or on holidays. Repair and installation prices are quoted upfront before work begins."})});script.textContent=JSON.stringify(data)}catch(_e){}});
document.querySelectorAll(".option-radio").forEach(option=>{const name=option.querySelector(".option-radio-name"),price=option.querySelector(".option-radio-price");if(!name||!price)return;if(name.textContent.includes("Residential Home"))price.textContent="Service call shown below";if(/Military|Senior Citizen|Police \/ Fire \/ EMS/.test(name.textContent))price.textContent="−10%"});
const discountHeading=[...document.querySelectorAll(".calc-options div")].find(el=>el.textContent.trim()==="🎖️ Discount (if applicable)");if(discountHeading)discountHeading.textContent="🎖️ Discount — 10% if applicable (one discount per job)";
const timing=document.querySelector(".calc-timing");if(timing)timing.innerHTML='<button class="timing-btn active" onclick="selectTiming(this,\'regular\',79)"><strong>Regular Hours — $79</strong><span>Mon–Fri · 9 AM–5 PM</span></button><button class="timing-btn" onclick="selectTiming(this,\'after\',99)"><strong>After Hours / Weekend — $99</strong><span>Weekdays after 5 PM + weekends</span></button><button class="timing-btn" onclick="selectTiming(this,\'midnight\',158)"><strong>After Midnight — $158</strong><span>Midnight until regular hours</span></button><button class="timing-btn" onclick="selectTiming(this,\'holiday\',158)"><strong>Holiday Service — $158</strong><span>Any holiday service call</span></button>';
const timingHeading=timing?.parentElement?.querySelector('div[style*="font-weight:700"]');if(timingHeading)timingHeading.textContent="🕐 Service / Diagnostic Call";
const wh=[...document.querySelectorAll("#calc-water-heater .calc-service-btn")],repair=wh.find(b=>b.textContent.includes("Water Heater Repair")),forty=wh.find(b=>b.textContent.includes("Replace 40-Gal Tank"));if(repair){const r=repair.querySelector(".range");if(r)r.textContent="From $149";repair.onclick=()=>window.selectService(repair,"Water Heater Repair",149,null)}if(forty){const r=forty.querySelector(".range");if(r)r.textContent="From $1,699";forty.onclick=()=>window.selectService(forty,"Replace 40-Gal Tank",1699,null)}
const resultLabel=document.querySelector(".calc-result-label");if(resultLabel)resultLabel.textContent="Your estimated total";const baseLabel=document.getElementById("bd-base")?.previousElementSibling;if(baseLabel)baseLabel.textContent="Repair / installation";const surcharge=document.getElementById("bd-surcharge"),surchargeLabel=surcharge?.previousElementSibling;if(surchargeLabel)surchargeLabel.textContent="Service / diagnostic call";const totalLabel=document.getElementById("bd-total")?.previousElementSibling;if(totalLabel)totalLabel.textContent="Estimated total";const disclaimer=document.querySelector(".calc-disclaimer");if(disclaimer)disclaimer.textContent="* Estimated total includes the selected service/diagnostic call and the repair/install estimate. Regular service calls are $79 Monday–Friday 9 AM–5 PM; after-hours and weekend calls are $99; after-midnight and holiday calls are $158. Final repair price is confirmed before work begins. Code-required upgrades, special materials or conditions outside normal scope are quoted before authorization."}
addLakeAreaLinks();updatePricingPageCopy();if(!document.querySelector(".calc-wrapper"))return;
const state={serviceName:"Toilet Repair",low:89,high:149,property:"residential",propertyAdj:0,timing:"regular",serviceCallFee:CONFIG.serviceCallFees.regular,discount:"none",discountPercent:0};
window.setCalcTab=(name,button)=>{document.querySelectorAll(".calc-tab").forEach(t=>t.classList.remove("active"));button.classList.add("active");document.querySelectorAll(".calc-tab-content").forEach(c=>c.style.display="none");const target=document.getElementById("calc-"+name);if(target)target.style.display="block"};
window.selectService=(button,name,low,high)=>{document.querySelectorAll(".calc-service-btn").forEach(i=>i.classList.remove("selected"));button.classList.add("selected");state.serviceName=name;state.low=Number.isFinite(Number(low))?Number(low):null;state.high=high===null||high===undefined||high===""?null:Number(high);update()};
window.selectOption=(button,type,value,adjustment)=>{button.parentElement.querySelectorAll(".option-radio").forEach(i=>i.classList.remove("selected"));button.classList.add("selected");if(type==="property"){state.property=value;state.propertyAdj=Number(adjustment)||0}if(type==="discount"){state.discount=value;state.discountPercent=value==="none"?0:CONFIG.discountPercent}update()};
window.selectTiming=(button,value,fee)=>{document.querySelectorAll(".timing-btn").forEach(i=>i.classList.remove("active"));button.classList.add("active");state.timing=value;state.serviceCallFee=Number(fee)||CONFIG.serviceCallFees.regular;update()};window.printEstimate=()=>window.print();
function timingLabel(){return state.timing==="regular"?"Regular Hours":state.timing==="after"?"After Hours / Weekend":state.timing==="midnight"?"After Midnight":"Holiday Service"}
function update(){const rawLow=scaled(state.low),rawHigh=scaled(state.high),propertyAdj=scaled(state.propertyAdj)||0,serviceCall=scaled(state.serviceCallFee)||0;let repairLow=rawLow===null?null:rawLow+propertyAdj,repairHigh=rawHigh===null?null:rawHigh+propertyAdj;const discountLow=repairLow!==null?Math.round(repairLow*(state.discountPercent/100)):0,discountHigh=repairHigh!==null?Math.round(repairHigh*(state.discountPercent/100)):0;if(repairLow!==null)repairLow=Math.max(49,repairLow-discountLow);if(repairHigh!==null)repairHigh=Math.max(repairLow||49,repairHigh-discountHigh);const totalLow=repairLow===null?null:repairLow+serviceCall,totalHigh=repairHigh===null?null:repairHigh+serviceCall,display=document.getElementById("calcPriceDisplay"),sub=document.getElementById("calcPriceSub");if(display)display.textContent=rangeText(totalLow,totalHigh);if(sub)sub.textContent=state.serviceName+" · "+timingLabel()+" · "+(state.property==="residential"?"Residential":"Commercial");const base=document.getElementById("bd-base");if(base)base.textContent=rangeText(rawLow,rawHigh);const surcharge=document.getElementById("bd-surcharge");if(surcharge)surcharge.textContent=money(serviceCall);const commercial=document.getElementById("bd-commercial");if(commercial)commercial.textContent=propertyAdj?"+"+money(propertyAdj):"$0";const discount=document.getElementById("bd-discount");if(discount)discount.textContent=state.discountPercent?"−"+state.discountPercent+"%":"$0";const discountLabel=document.getElementById("bd-discount-label");if(discountLabel)discountLabel.textContent=state.discount==="none"?"Discount":"Discount ("+state.discount+")";const total=document.getElementById("bd-total");if(total)total.textContent=rangeText(totalLow,totalHigh)}
update();
})();
