const SUPABASE_URL='https://wuwgvtjktppjueiykcww.supabase.co';
const SUPABASE_KEY='sb_publishable_GDRVKaxxwvFuV7jhldebYA_6GjUszub';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmtDate=v=>v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function msg(text,error=false){const el=$('#authMsg');el.textContent=text;el.classList.remove('hidden','error');if(error)el.classList.add('error')}
function empty(text='Nothing here yet.'){return `<div class="empty">${esc(text)}</div>`}
function pill(v){return `<span class="pill ${esc(v)}">${esc(v||'—')}</span>`}
function table(headers,rows){if(!rows.length)return empty();return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}

async function profile(){const {data:{user}}=await sb.auth.getUser();if(!user)return null;const {data,error}=await sb.from('crm_users').select('*').eq('id',user.id).maybeSingle();if(error)throw error;return data}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){showAuth();return}try{const p=await profile();if(!p||!p.active){showAuth();$('#claimForm').classList.remove('hidden');msg('Your login exists. Enter the owner setup code to activate PP911 Operations.');return}showApp();await refreshAll()}catch(e){console.error(e);showAuth();msg(e.message||'Could not load account',true)}}
function showAuth(){$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}
function showApp(){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden')}

$('#authForm').addEventListener('submit',async e=>{e.preventDefault();msg('Signing in…');const email=$('#email').value.trim(),password=$('#password').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)return msg(error.message,true);await boot()});
$('#signupBtn').addEventListener('click',async()=>{const email=$('#email').value.trim(),password=$('#password').value,full_name=$('#fullName').value.trim()||'Owner';if(!email||password.length<8)return msg('Enter your email and a password of at least 8 characters.',true);msg('Creating your login…');const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name}}});if(error)return msg(error.message,true);if(!data.session)return msg('Login created. Check your email for the confirmation link, then come back and sign in.');$('#claimForm').classList.remove('hidden');msg('Login created. Enter the owner setup code below.')});
$('#claimForm').addEventListener('submit',async e=>{e.preventDefault();const code=$('#claimCode').value.trim();const {data,error}=await sb.rpc('claim_ops_owner',{p_code:code});if(error)return msg(error.message,true);msg('Owner access activated. Loading PP911 Operations…');setTimeout(boot,500)});
$('#signOutBtn').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
$('#refreshBtn').addEventListener('click',refreshAll);

$$('#tabs button').forEach(b=>b.addEventListener('click',()=>{$$('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active')}));
$$('[data-modal]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.modal).showModal()));

async function q(tableName,select='*',opts={}){let r=sb.from(tableName).select(select);if(opts.order)r=r.order(opts.order,{ascending:opts.asc??false});if(opts.limit)r=r.limit(opts.limit);const {data,error}=await r;if(error)throw error;return data||[]}
async function count(tableName){const {count,error}=await sb.from(tableName).select('*',{count:'exact',head:true});if(error)throw error;return count||0}

async function refreshAll(){try{const [leadCount,customerCount,jobCount,dispatchCount,leads,calls,customers,appointments,jobs,dispatch,prices,invoices]=await Promise.all([
count('leads'),count('customers'),count('work_orders'),count('dispatch_tickets'),
q('leads','*',{order:'created_at',limit:50}),q('call_sessions','*',{order:'created_at',limit:50}),q('customers','*',{order:'created_at',limit:100}),q('appointments','*',{order:'scheduled_start',asc:true,limit:100}),q('work_orders','*',{order:'created_at',limit:100}),q('dispatch_tickets','*',{order:'created_at',limit:100}),q('price_book_items','*',{order:'category',asc:true,limit:500}),q('invoices','*',{order:'created_at',limit:100})]);
renderStats({leadCount,customerCount,jobCount,dispatchCount});renderLeads(leads);renderCalls(calls);renderCustomers(customers);renderSchedule(appointments);renderJobs(jobs);renderDispatch(dispatch);renderPricing(prices);renderInvoices(invoices)}catch(e){console.error(e);alert('Could not refresh PP911 Operations: '+e.message)}}

function renderStats(s){$('#stats').innerHTML=[['Leads',s.leadCount],['Customers',s.customerCount],['Open jobs',s.jobCount],['Dispatch tickets',s.dispatchCount]].map(([l,n])=>`<div class="stat"><div class="num">${n}</div><div class="label">${l}</div></div>`).join('')}
function renderLeads(data){$('#dashboardLeads').innerHTML=data.slice(0,6).length?`<div class="mini-list">${data.slice(0,6).map(x=>`<div class="mini-item"><div class="mini-title">${esc(x.caller_name||x.phone)}</div><div>${esc(x.issue_summary)}</div><div class="mini-meta">${pill(x.urgency)} · ${fmtDate(x.created_at)}</div></div>`).join('')}</div>`:empty('No leads yet.');$('#leadsTable').innerHTML=table(['Customer','Phone','Issue','Urgency','Status','Created'],data.map(x=>`<tr><td>${esc(x.caller_name||'—')}</td><td>${esc(x.phone)}</td><td>${esc(x.issue_summary)}</td><td>${pill(x.urgency)}</td><td><select class="status-select lead-status" data-id="${x.id}">${['new','contacted','qualified','booked','lost','spam'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></td><td>${fmtDate(x.created_at)}</td></tr>`));$$('.lead-status').forEach(s=>s.addEventListener('change',async()=>{const {error}=await sb.from('leads').update({status:s.value}).eq('id',s.dataset.id);if(error)alert(error.message)}))}
function renderCalls(data){$('#dashboardCalls').innerHTML=data.slice(0,6).length?`<div class="mini-list">${data.slice(0,6).map(x=>`<div class="mini-item"><div class="mini-title">${esc(x.caller_name||x.caller_phone||'Unknown caller')}</div><div>${esc(x.ai_summary||x.disposition||'Call recorded')}</div><div class="mini-meta">${pill(x.status)} · ${fmtDate(x.created_at)}</div></div>`).join('')}</div>`:empty('No calls recorded yet.');$('#callsTable').innerHTML=table(['Caller','Phone','Status','Emergency','Summary','Started'],data.map(x=>`<tr><td>${esc(x.caller_name||'—')}</td><td>${esc(x.caller_phone||'—')}</td><td>${pill(x.status)}</td><td>${x.emergency?'Yes':'No'}</td><td>${esc(x.ai_summary||x.disposition||'—')}</td><td>${fmtDate(x.started_at||x.created_at)}</td></tr>`))}
function renderCustomers(data){$('#customersTable').innerHTML=table(['Name','Company','Phone','Email','Source','Created'],data.map(x=>`<tr><td><strong>${esc(x.first_name)} ${esc(x.last_name)}</strong></td><td>${esc(x.company_name||'—')}</td><td>${esc(x.phone)}</td><td>${esc(x.email||'—')}</td><td>${esc(x.source||'—')}</td><td>${fmtDate(x.created_at)}</td></tr>`))}
function renderSchedule(data){$('#scheduleTable').innerHTML=table(['Start','Status','Service','Problem','Arrival window'],data.map(x=>`<tr><td>${fmtDate(x.scheduled_start)}</td><td>${pill(x.status)}</td><td>${esc(x.service_category||'—')}</td><td>${esc(x.problem_description||'—')}</td><td>${esc(x.arrival_window_minutes)} min</td></tr>`))}
function renderJobs(data){$('#jobsTable').innerHTML=table(['WO #','Status','Complaint','Diagnosis','Work performed','Created'],data.map(x=>`<tr><td><strong>#${esc(x.work_order_number)}</strong></td><td><select class="status-select job-status" data-id="${x.id}">${['open','diagnosing','quoted','approved','in_progress','completed','cancelled'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></td><td>${esc(x.complaint||'—')}</td><td>${esc(x.diagnosis||'—')}</td><td>${esc(x.work_performed||'—')}</td><td>${fmtDate(x.created_at)}</td></tr>`));$$('.job-status').forEach(s=>s.addEventListener('change',async()=>{const patch={status:s.value};if(s.value==='completed')patch.completed_at=new Date().toISOString();const {error}=await sb.from('work_orders').update(patch).eq('id',s.dataset.id);if(error)alert(error.message)}))}
function renderDispatch(data){$('#dispatchTable').innerHTML=table(['Ticket','Urgency','Status','Caller','Phone','City','Issue','Created'],data.map(x=>`<tr><td>#${esc(x.ticket_number)}</td><td>${pill(x.urgency)}</td><td>${pill(x.status)}</td><td>${esc(x.caller_name||'—')}</td><td>${esc(x.caller_phone)}</td><td>${esc(x.city)}</td><td>${esc(x.issue_summary)}</td><td>${fmtDate(x.created_at)}</td></tr>`))}
function renderPricing(data){$('#pricingTable').innerHTML=table(['Category','Service','Option','Standard','Member','Minutes'],data.map(x=>`<tr><td>${esc(x.category)}</td><td><strong>${esc(x.service_name)}</strong><br><span class="muted">${esc(x.description||'')}</span></td><td>${esc(x.option_level)}</td><td>$${Number(x.standard_price||0).toLocaleString()}</td><td>${x.member_price!=null?'$'+Number(x.member_price).toLocaleString():'—'}</td><td>${esc(x.estimated_minutes||'—')}</td></tr>`))}
function renderInvoices(data){$('#invoicesTable').innerHTML=table(['Invoice','Title','Status','Total','Paid','Due'],data.map(x=>`<tr><td>#${esc(x.invoice_number)}</td><td>${esc(x.title)}</td><td>${pill(x.status)}</td><td>$${Number(x.total||0).toFixed(2)}</td><td>$${Number(x.amount_paid||0).toFixed(2)}</td><td>${esc(x.due_date||'—')}</td></tr>`))}

$('#saveLeadBtn').addEventListener('click',async()=>{const fd=new FormData($('#leadForm')),row=Object.fromEntries(fd.entries());row.source='office_manual';row.status='new';const {error}=await sb.from('leads').insert(row);if(error)return alert(error.message);$('#leadModal').close();$('#leadForm').reset();await refreshAll()});
$('#saveCustomerBtn').addEventListener('click',async()=>{const fd=new FormData($('#customerForm'));const row=Object.fromEntries(fd.entries());const address=row.address_line1,city=row.city,postal=row.postal_code;delete row.address_line1;delete row.city;delete row.postal_code;row.source='office_manual';const {data,error}=await sb.from('customers').insert(row).select('id').single();if(error)return alert(error.message);if(address&&city){const {error:pe}=await sb.from('properties').insert({customer_id:data.id,address_line1:address,city,state:'SC',postal_code:postal||null});if(pe)alert('Customer saved, but address could not be saved: '+pe.message)}$('#customerModal').close();$('#customerForm').reset();await refreshAll()});

if('serviceWorker' in navigator)navigator.serviceWorker.register('/ops/sw.js').catch(()=>{});
sb.auth.onAuthStateChange(()=>setTimeout(boot,0));
boot();